### ISSUE TITLE
Icons are cut of on a 4k Screen

### ISSUE THREAD

**Issue by Keb0ir** [rmountjoy92/DashMachine#103]
As the Title already says the Icons on the dash are getting cut of on my 4k Screen. If i turn the Scaling to 175 the Scrollbars disappear or when i put the browser on my Full HD secondary screen.

![Screenshot from 2020-04-06 01-40-07](https://user-images.githubusercontent.com/34890046/78512778-961dca80-77a7-11ea-8fe9-5020552ac518.png)

**Comment by marcjmiller** [comment]
Oof, didn't have secondary FHD to test scrollbars behavior...

**Comment by rmountjoy92** [comment]
fixed in 62191b21b88218b67042517621dfb2e6088b4c4e
