### ISSUE TITLE
Login page doesn't autofocus Username input field

### ISSUE THREAD

**Issue by marcjmiller** [rmountjoy92/DashMachine#121]
Simple request, the login form displays but you have to select the first field to input your username.

https://github.com/rmountjoy92/DashMachine/blob/a01a7b911e0800f6b65e81f7c088531f5d3912d4/dashmachine/templates/user/login.html#L17

At this line, add an `autofocus=true` should do the trick.  I'll submit a PR later when I'm not 'working from home'.

**Comment by rmountjoy92** [comment]
fixed in 62191b21b88218b67042517621dfb2e6088b4c4e
