### ISSUE TITLE
Worker timeout

### ISSUE THREAD

**Issue by Zciwobukaj** [rmountjoy92/DashMachine#123]
Editing config.ini and suddenly having this : 
![image](https://user-images.githubusercontent.com/35924688/79037358-6a984700-7bd0-11ea-95dd-fb31a863533a.png)

When I come back to default config.ini and reboot docker container, this works once again.
When I restore my previous config.ini (copy paste of content inside the online editor), I have the same error messages.

**Comment by Zciwobukaj** [comment]
Somehow I manage to find a workaround to this situation : 
I change to startup script in this way : 

gunicorn --bind 0.0.0.0:5000 **-t 300** wsgi:app

Default timeout of worker is 30s, and this becomes too short when Dashmachine has too much content to manage.
To extend timeout to 300s gives enough time to worker to perform their task. But I'm not sure this is viable solution...

**Comment by rmountjoy92** [comment]
Hmm, have not seen that error yet. I will make this change in on develop and see if there are any consequences.
