### ISSUE TITLE
[ENHANCEMENT] Individual tags_expanded setting

### ISSUE THREAD

**Issue by BadCo-NZ** [rmountjoy92/DashMachine#138]
Being able to set 'tags_expanded' per tag rather then in bulk.

This will enable us to hide away uncommon links and keep for commonly used ones visible and minimise scrolling.

By the way rmountjoy92, I have come form Heimdall, and DashMachine is a huge step up, keep up the solid work!

**Comment by rmountjoy92** [comment]
fixed in 62191b21b88218b67042517621dfb2e6088b4c4e
