### ISSUE TITLE
[Bug] Weird issue when loading Dash Machine home page in iframe

### ISSUE THREAD

**Issue by ghzgod** [rmountjoy92/DashMachine#140]
First and foremost, this is NOT to be confused with opening a dashmachine link in iframe.  I understand that is an issue with the links themselves.  This is referring to opening dashmachine itself into an iframe. 

I use an addon in Firefox to load a URL when a new tab is opened.  This allows me to see dashmachine each time I open a new tab.  

The addon specifically is here https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab-page/?src=search

This addon uses an iframe so the address bar is auto selected after the tab is open.  I notice that dashmachine loads with the addon but the theme is white (can't change) and a lot of the page elements are not rendered properly. [See Image](https://imgur.com/a/Q1qyCL4).  This image shows how the config.ini doesn't render when looking at settings on the right side for example. I believe this is a bug with rendering dashmachine as an iframe which could have potential issues with other applications.

**Comment by rmountjoy92** [comment]
Opening DM in an iframe sounds like an unneeded complication to me. I would suggest using a new tab extension that just passes a url to the new tab like this one:
https://chrome.google.com/webstore/detail/custom-new-tab-url/mmjbdbjnoablegbkcklggeknkfcjkjia

**Comment by ghzgod** [comment]
> Opening DM in an iframe sounds like an unneeded complication to me. I would suggest using a new tab extension that just passes a url to the new tab like this one:
> https://chrome.google.com/webstore/detail/custom-new-tab-url/mmjbdbjnoablegbkcklggeknkfcjkjia

That's the extension I use, the way it passes the URL is through an iframe because it pulls focus back to the address bar like opening a tab normally.  In DM's current state, focus turns to the **search apps box** due to your home.html line

`<input type="text" id="apps-filter" class="card-filter theme-surface-transparent" placeholder="Search apps" autofocus>`
