### ISSUE TITLE
Settings tab adds additional newline each time I save

### ISSUE THREAD

**Issue by Kickbut101** [rmountjoy92/DashMachine#142]
For whatever reason when I go to save the config.ini settings through the browser interface (Chrome) I will let it reload and then every single line ending/newline has an _additional_ newline after it. So after saving 2-3 times now I have lots and lots of whitespace between each line.

**Comment by rmountjoy92** [comment]
fixed in 62191b21b88218b67042517621dfb2e6088b4c4e
