### ISSUE TITLE
[Enhancement] Comments on config file

### ISSUE THREAD

**Issue by Thlb** [rmountjoy92/DashMachine#144]
Comments on config file are removed while saving.

This could be useful for :
- organizing config file
- disabling cards/data temporarly

**Comment by rmountjoy92** [comment]
Unfortunately, Configparser (the python backend module that parses the ini file) wipes out comments whenever you modify the ini using Configparser. My solutions for this is:

- 0.6 includes GUI forms for editing each type of item in the config (ie Settings form, Users form, Card editor/creator, etc) be on the lookout on reddit this week for an update on reddit for 0.6 to see this in action
- In the next version after 0.6, I plan to add a 'repository sync' feature where you can host your config file as like a github gist or something (where you could have comments)
