### ISSUE TITLE
[ENHANCEMENT] Change tags select to a multi-select

### ISSUE THREAD

**Issue by BadCo-NZ** [rmountjoy92/DashMachine#145]
Hi,

At the moment the 'Tags' drop bar next to the search bar can expand the tags by clicking 'All Tags'.

Unfortunately once you expand them all they can only be collapsed by individually clicking them on them, it would be usefull no have a Collapse All/Expand All, or All Tags/No Tags.

Thanks!

**Comment by rmountjoy92** [comment]
added in 62191b21b88218b67042517621dfb2e6088b4c4e
