### ISSUE TITLE
[BUG] #commenting a line removes it

### ISSUE THREAD

**Issue by BadCo-NZ** [rmountjoy92/DashMachine#146]
As per title. I'm not sure if this was intentional, but I was trying to decide what icons to have in the side bar, so I went through and commented out a few with the intention of maybe changing my mind down the track.

Obviously it just removed them completely instead haha

Any chance of making commented lines persistant?

**Comment by BadCo-NZ** [comment]
Just realised this is a repeat of #144 

Sorry for the spam

**Comment by rmountjoy92** [comment]
No worries, closing :)
