### ISSUE TITLE
[DOCUMENTATION] Sidebar Icon Size

### ISSUE THREAD

**Issue by BadCo-NZ** [rmountjoy92/DashMachine#147]
Is there a specific size for the side bar icons? Also, for card icons?

See attached image for icon size issues :)

![dashmachine2](https://user-images.githubusercontent.com/50016048/79864374-79cb9000-842d-11ea-9a9b-df87de2f46d0.PNG)

**Comment by BadCo-NZ** [comment]
I did find this in the contributers template, updated the title.

`[ ] I'm submitting a template app

    I have added a .ini file to DashMachine with the same name used for [App Name] in the .ini file (e.g. 'App Name.ini')
    My .ini has the exact format as the others in the folder, only changing the name, icon location, and description.
    I used the official description and name for the app, found on their repository/website.
    I chose an icon (.png file) sized over 64px, with a transparent background, square aspect ratio, preferably the icon only version (not icon w/ text) of the app's icon.
    I understand that the icon will be resized to 64px x 64px and have verified that it looks good at that size.
    I have added the icon to static/images/apps with the correct name matching what's in the .ini.
    I tested it to make sure it looks good in the interface
`

**Comment by rmountjoy92** [comment]
So, I probably need to state this in the docs, but there are a few different folders that DM looks for images from,

`static/images/apps` is the folder that template apps use to source their icons - these are reduced to 64x64px automatically these are not intended to be edited by the user, as any changes will be wiped out with updates. 

`static/images/icons` and `static/images/backgrounds` are linked to the `images` and `backgrounds` folders in your `user_data` folder and are not modified in any way by DM (besides setting the height attribute when they're displayed). `user_data` persists updates.

When you upload a image in /settings it goes to either `static/images/icons` or `static/images/backgrounds` (depending on which folder you select on the form). If you are using a custom icon, it's best to use a square geometry (ie, 64,64). You are free to use images of any size, but as with any image, you must balance how large the photo is (load time) vs quality.

**Comment by BadCo-NZ** [comment]
Awesome, thanks for the reply!
