### ISSUE TITLE
Sub grouping

### ISSUE THREAD

**Issue by arejaytee** [rmountjoy92/DashMachine#148]
To be able to classify each entry to a group and contain them together, for example

Surveillance - Camera's
Media - Plex/Emby
Infrastructure - Routers/Modem/AP/Servers

**Comment by rmountjoy92** [comment]
DashMachine has this ability currently, in your app entry:
`tags = Media`

**Comment by arejaytee** [comment]
Thanks sorry I should have read a bit harder
