### ISSUE TITLE
[Bug] Icon not being updated on reupload

### ISSUE THREAD

**Issue by nrgbistro** [rmountjoy92/DashMachine#155]
Steps to reproduce:

1. Upload icon
2. Decide icon doesn't look right
3. Delete icon
4. Upload different/altered icon with the same filename
5. The original icon still shows up

This is somewhat annoying when trying to create custom icons for applications because I have to create a new filename for every iteration of the icon I make. It seems like the only icon gets stuck somewhere and isn't really being deleted.

**Comment by rmountjoy92** [comment]
Do a hard reload, on chrome its ctrl+shift+r

**Comment by nrgbistro** [comment]
I did ctrl+shift+r and I still get the same behavior.
