### ISSUE TITLE
Dashboard unresponsive while unsuccessful ping is running

### ISSUE THREAD

**Issue by Chrismettal** [rmountjoy92/DashMachine#16]
When configuring an app to show the online status of a service which is not online the ping function will wait for a few seconds before showing the "offline" state. This is no problem, but the whole dashboard will not respond as long as the ping is still doing the "loading circle" thingy. I ping multiple services which are rarely running, so basically every time i visit the dashboard i have to wait a few seconds before doing anything useful.

**Comment by rmountjoy92** [comment]
I was able to reproduce this, added to roadmap :smile:
