### ISSUE TITLE
CI/CD: Add tags to docker image instead :latest

### ISSUE THREAD

**Issue by ebarped** [rmountjoy92/DashMachine#160]
Hello

Im wondering if it´s possible to tag the docker image that is uploaded to Docker Hub.

I think the best approach is to use the same build number you use in your releases.

Right now the build version is v0.5-4, so we could use
`docker pull rmountjoy/dashmachine:v0.5-4`

This could give the users a control of the version whenever they redeploy this applicattion.

Thanks in advance!

**Comment by rmountjoy92** [comment]
Done :smile:
