### ISSUE TITLE
/bin/sh: 1: [: gunicorn,: unexpected operator

### ISSUE THREAD

**Issue by Famku** [rmountjoy92/DashMachine#162]
Hi,

unfortunately I receive this error message in docker on 0.6 develop

Testet on Ubuntu and Synology

can you please check

**Comment by rmountjoy92** [comment]
Still working on a lot of issues with 0.6. I wouldn't test it out quite yet. Keep an eye out on the Reddit, I'll make an announcement when it's ready to go.

**Comment by Famku** [comment]
OK, thanks

**Comment by rmountjoy92** [comment]
@Famku okay, I think I got most of the big problems, repull the image and let me know if you have any issues :)

**Comment by ThelloD** [comment]
Pulled the latest image (`dashmachine:develop`) but have the same issue. 

```
# docker-compose down
...
# docker-compose pull
Pulling dashmachine ... done
# docker-compose up
...
Creating dashmachineDEV ... done
Attaching to dashmachineDEV
dashmachineDEV | /bin/sh: 1: [: gunicorn,: unexpected operator

dashmachineDEV exited with code 2
```

Tried to run with empty data directory and no attached volumes at all, still won’t come up. 

Is the latest build broken or am I missing something?

**Comment by rmountjoy92** [comment]
Give it another try, I think one of the the CMD arguments having single quotes instead of double quotes was throwing things off, I made the change and rebuilt.

**Comment by ThelloD** [comment]
Thanks, the old error is gone but unfortunately the following error is now shown:

    Attaching to dashmachineDEV
    dashmachineDEV | usage: gunicorn [OPTIONS] [APP_MODULE]
    dashmachineDEV | gunicorn: error: argument -b/--bind: expected one argument

Seems that the current version needs same arguments to be passed? 
I’m currently on the go and only gave it a try by SSHing into my machine. Guess tomorrow evening or on Monday I could look a bit deeper into the issue. 

Btw, I’m using plain docker-compose.yml on the command line, no portainer etc. is involved.

**Comment by rmountjoy92** [comment]
Hmm i see, i think i just fixed it. Sorry about that, try it again.

**Comment by ThelloD** [comment]
Thank you, dashmachine is loading fine now! :slightly_smiling_face:
Not sure why, but loading it the first time took a very long time, but now it's fine.

Btw, I already noticed a minor issue, do you want that we create separate issues for every bug no matter how small or would you rather prefer a summary of our observations?
(In this case, it's that the info message with the changelog shows up on (nearly) every click although the button "Later" was pressed. The message should only show up again after a while and not every time the user clicks a link.)
