### ISSUE TITLE
[docker] loading app in iframe doesn't connect to site

### ISSUE THREAD

**Issue by MayhemBill** [rmountjoy92/DashMachine#165]
whenever I add an app with a website loading in an iframe it doesn't connect, I tried several websites (github/facebook/google) and they don't connect, but DM loads fine.

**Comment by runnylogan** [comment]
Many sites and local applications actively block loading in an iframe as its a security risk. I don't think this is related to DM.

**Comment by id-ic** [comment]
Has anyone setup a HTTPS proxy (nginx or something) to make this connection for the dashboard?

**Comment by MayhemBill** [comment]
Chrome is actively blocking the iframe being loaded by DM, I installed an extension called iFrame Allow, and it loaded no problem.
