### ISSUE TITLE
Reverse proxy of DashMachine for NGINX not working

### ISSUE THREAD

**Issue by spiral6** [rmountjoy92/DashMachine#18]
For example, if the URL is `http://example.com/dashmachine`,

Static assets such as `images/cards/applewatch.png` are loading at `http://example.com/images/cards/applewatch.png`, not `http://example.com/dashmachine/images/cards/applewatch.png`.

**Comment by rmountjoy92** [comment]
I use nginx as a proxy and it works fine, but I use subdomains, not paths. I would post questions about nginx on stackoverflow.

**Comment by spiral6** [comment]
I wouldn't consider this a solution. There are issues with assets being loaded incorrectly that are relative to the host site as opposed to a subpage. There should be complete, relative asset support as an option either in the .ini file or under the Docker environmental option. The subpage option for Docker only creates a new subpage independent of the host. 

So even if `example.com/dashmachine` was set inside of the NGINX reverse proxy and `/dashmachine` is set as the subpage option for DashMachine, it will attempt to load it on `example.com/dashmachine/dashmachine` which isn't the intended effect.

**Comment by stefancyliax** [comment]
Trying to use Dashmachine behind Traefik with paths. Also not working. Looks like its the same problem. I need to do more debugging though.

**Comment by di-dc** [comment]
I use the docker image + the linuxserver letsencrypt container, and am able to run it at https://mydomain.tld/dash. My setup:

DashMachine: I have the environment var CONTEXT_PATH set to "/dash"

Then in nginx my DashMachine-related configs (copying the patterns used by their other configs for consistency) are:

```
location /dash {
	return 301 $scheme://$host/dash/;
}

location ^~ /dash/ {	
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app dashmachine;
	set $upstream_port 5000;
	set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

**Comment by di-dc** [comment]
Also, does _/images/cards/applewatch.png_ actually exist? (Or really, do those bg-image-x CSS tags in style.css ever get used, or can they be removed?)

**Comment by rmountjoy92** [comment]
> Also, does _/images/cards/applewatch.png_ actually exist? (Or really, do those bg-image-x CSS tags in style.css ever get used, or can they be removed?)

So when I first started working on the project that this is forked from, I used a materialize css theme to learn how materialize works. There is leftover css that needs to be cleaned out from the theme.

**Comment by spiral6** [comment]
@di-dc What would the `proxy.conf` in your snippet define?

**Comment by di-dc** [comment]
@spiral6 Should be the same (or at least very very close) to the default here:
https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/nginx.conf

And in case it matters: to clarify an earlier post, in my docker compose file the context_path is not in quotes:
```
    environment:
      - CONTEXT_PATH=/dash
```

**Comment by spiral6** [comment]
Will report back after testing.

**Comment by spiral6** [comment]
Seems like everything's working except for the backgrounds. I'm not certain why that's occurring.

`index.js:1200 GET http://openmediavault/static/images/backgrounds/custom.png 404 (Not Found)`

**Comment by di-dc** [comment]
Glad it's working. Looks like the paths for the background images need to be updated to include the context_path (if set); I don't use background images, so hadn't noticed.
