### ISSUE TITLE
Allow basic users to access home page

### ISSUE THREAD

**Issue by roooxvee** [rmountjoy92/DashMachine#19]
Hello.
I have a problem with accessing home page with basic user.
When i try to login with basic user i receive unauthorized message.
Please help me.
My conf:

[Settings]
theme = dark
accent = green
background = None
home_access_groups = admins, users
roles = admin, user, power_user
settings_access_groups = admin_only
[users]
roles = user, admin, power_user
[admins]
roles = admin
[power_users]
roles = power_user, user
[Radarr]
prefix = https://
groups = admins
url = radarr.harej.org
description = Radarr is system for automatically downloading movies via Usenet and BitTorrent.
open_in = iframe
icon = static/images/icons/radarr.png
[Nextcloud]
prefix = https://
groups = admins, users, power_users
url = cloud.harej.org
icon = static/images/apps/nextcloud.png
sidebar_icon = static/images/apps/nextcloud.png
description = A safe home for all your data – community-driven, free & open source
open_in = new_tab

**Comment by rmountjoy92** [comment]
From the readme:

Say we wanted to create a limited user that still has a login, but can only access /home and certain apps we would first create a group:

[users]
roles = admin, user
then we would change in the [Settings] entry:

home_access_groups = users
By default here, the user user could access /home, but would see no apps. To allow access, we would add to apps:

groups = users
Say we then wanted to allow some access for users without a login (public_user), we would add:

[public]
roles = admin, user, public_user
then we would change in the [Settings] entry:

home_access_groups = public
By default here, the public_user user could access /home, but would see no apps. To allow access, we would add to apps:

groups = public
It’s also important to note, when setting up roles in [Settings], say we had roles set like this:

roles = my_people
**Dashmachine will automatically add admin,user,public_user, so really you would have 4 roles: my_people,admin,user,public_user. Also, the admin_only group is required and added by default if omitted.**
