### ISSUE TITLE
Linux Service and Updates

### ISSUE THREAD

**Issue by kb8cb40j1av39c02** [rmountjoy92/DashMachine#200]
Hello,

I have almost 0 experience with docker and most of my machines are Linux Containers (LXC) or Virtual Machines. I followed the instructions for linux and successfully installed DashMachine - so far so good.

Are there any good instructions on setting up a systemd service for running DashMachine automatically on starting Linux, in my case Ubuntu? I have tried following - but it sadly doesn't work:
                                                                                               
```
[Unit]
Description=dashmachine
After=multi-user.target

[Service]
Type=idle
ExecStart=/home/user/DashMachineEnv/bin/activate /home/user/DashMachineEnv/DashMachine/run.py

[Install]
WantedBy=multi-user.target
```

Apart from that, maybe more important - the instructions for updating DashMachine without docker are "For python, use git.". How exactly would that work, with which commands?

I have tried to google first before posting here but I haven't had much success. Any help would be appreciated.

cheers

**Comment by marcjmiller** [comment]
If you previously grabbed the source via `git clone github.com/rmountjoy92/dashmachine.git` then to update you can go to the dashmachine root directory and run `git pull` to retrieve the updates from the github.  If that isn't how you retrieved the source, it's just a few extra steps before doing that.

**Comment by kb8cb40j1av39c02** [comment]
Thank you so much!

**Comment by kb8cb40j1av39c02** [comment]
Solved on [reddit](https://www.reddit.com/r/selfhosted/comments/jc7zdh/having_trouble_setting_up_dashmachine_as_a/).
