### ISSUE TITLE
[Request] Support for Application Categories

### ISSUE THREAD

**Issue by JulienBedel** [rmountjoy92/DashMachine#21]
Hi !

Thanks for all the great work you have been doing with this project, it's awesome !

The only thing I have been missing with the dashboard is the ability to categorize my applications, I thought of two ways in which this could be implemented :
- Titles above a group of apps that helps to distinguish the various categories
- Category boxes that expand and shows the applications inside once clicked

I kinda lack time and knowledge to make a pull request for the moment, but I hope this would give ideas to others that would enjoy this feature !

**Comment by di-dc** [comment]
Check out the "tags" option in the config.ini readme. Set the tags on apps, and then there's a dropdown at the top to select the tag, which filters the page to that tag only.

**Comment by JulienBedel** [comment]
@di-dc Thanks for your response ! I already knew about the tagging option, what I am describing is more about the possibility to have every category written directly in your home menu (in "sub-folders" or just with titles, as you can see in other dashboards like [Homer](https://raw.githubusercontent.com/bastienwirtz/homer/master/screenshot.png)), without having to use filters.

**Comment by rmountjoy92** [comment]
fixed in 00786d9eb63db46f30a6d395093d56fe2e97d673
