### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'roles'

### ISSUE THREAD

**Issue by j-porsche** [rmountjoy92/DashMachine#22]
I have a problem going into the settings inside the dashboard. I added my own needed websites and now I am not able to go to the settings in the dashboard. I can only change something inside the document in user_data. Can somebody help me with this problem?

**Comment by mike391** [comment]
Also getting this error on the latest

**Comment by di-dc** [comment]
What does the [Settings] section of your config.ini look like?

Default:
```
[Settings]
theme = light
accent = orange
background = None
roles = admin,user,public_user
home_access_groups = admin_only
settings_access_groups = admin_only
```

And, not 100% sure if it's needed or not, but you might have to define the "admin_only" group (the example below assumes your user is in the admin role):
```
[admin_only]
roles = admin
```

**Comment by di-dc** [comment]
And if that doesn't help, try this: https://github.com/rmountjoy92/DashMachine/issues/8
