### ISSUE TITLE
Broken images in Readme

### ISSUE THREAD

**Issue by RommelTJ** [rmountjoy92/DashMachine#23]
Just heard about DashMachine. Looks like your Readme has some broken images. I've attached a screenshot of what they look like. Would be nice to have screenshots to preview what the product looks like before installing and running it on my own server.

<img width="961" alt="Screen Shot 2020-03-06 at 9 22 43 AM" src="https://user-images.githubusercontent.com/2304077/76106697-3f488980-5f8c-11ea-913c-9f8b5877be34.png">

**Comment by rmountjoy92** [comment]
fixed in 00786d9eb63db46f30a6d395093d56fe2e97d673
