### ISSUE TITLE
Icon really is required

### ISSUE THREAD

**Issue by bdillahu** [rmountjoy92/DashMachine#27]
The config.ini readme says that Icon (and Sidebar icon) are not required, but if you don't have one, you get a:

`<img src="None" height="64px">`

in the HTML which appears (at least in my Firefox) as a "missing picture" type icon...

No biggie, but thought I would mention it.

**Comment by rmountjoy92** [comment]
Fixed in 1240664303d74d5d6cd81d2cebb80b3c1a534637
