### ISSUE TITLE
Tag Header and dropdown entry hide when not applicable

### ISSUE THREAD

**Issue by ianc125** [rmountjoy92/DashMachine#28]
The tag header and dropdown entry should hide from users when they are not applicable.

I have apps that certain users cant see but they keep seeing a blank header entry and dropdown entry when its not applicable to them at all.

**Comment by rmountjoy92** [comment]
fixed in 259068e6188d1423c03ec2a69a91979ae3113e90

**Comment by ianc125** [comment]
Thank you :)
