### ISSUE TITLE
Feature request: random background from Internet (r/Earthporn or simillar) and dynamic coloring

### ISSUE THREAD

**Issue by dmigis** [rmountjoy92/DashMachine#34]
It would be nice to fetch random background from Internet (r/Earthporn, UnSplash, EarthView, Bing, ChromeOS wallpapers and others) and adjust color pallete according to background (like pywal does (https://github.com/dylanaraps/pywal))

**Comment by Zciwobukaj** [comment]
Your need is partially fulfilled : 
`background = https://source.unsplash.com/random/1680x1050/?lightning`
(as an example of what is possible)

**Comment by rmountjoy92** [comment]
Easily done with unsplash or similar service.
