### ISSUE TITLE
Ability to "Ping" Services on non-standard ports

### ISSUE THREAD

**Issue by rmountjoy92** [rmountjoy92/DashMachine#4]
Hi,

I just started using DM. Its been great so far, coming from Heimdall and Homer.

The ping function works great overall, however I cant get it to reach certain internal services on specific ports. e.g. Portainer and Bazarr run on the same device, but on different ports.

Is there a way around this?

Closed : I just realised that ping only check if there is a response, it doesnt actually check if the service is running. Hence, closing this request.

**Comment by rmountjoy92** [comment]
When I first made ping, it used requests.get() and worked how you were expecting. But a true ping needs to use the ping command. I'm planning on adding requests.get() as an option for this platform. That way you could choose to ping or get.

**Comment by franznemeth** [comment]
This should be addressed by #48
