### ISSUE TITLE
Docker Internal Server Error 

### ISSUE THREAD

**Issue by king-gheedorah** [rmountjoy92/DashMachine#43]
After installing through Docker (either "latest" or "develop"), adding an app to config.ini causes a crash.

Docker log:
https://pastebin.com/xrYM8Cj4

EDIT:
This appears to be the same as Issue #41

**Comment by fosspill** [comment]
Experiencing the same issue after recent updates to the docker image. You are getting the error after upgrading or was it a clean install?

**Comment by fosspill** [comment]
After some more troubleshooting: Add a new app to the config instantly crashes dashmachine.
Not directly update related.

**Comment by byackee** [comment]
Hi,
Same for me, when adding a app in config.ini, app crash

**Comment by rmountjoy92** [comment]
this should be fixed in 3bd607a33d4b2b89430e8eb648e787813ddc345e please also read this: https://redd.it/flubzn
