### ISSUE TITLE
FEATURE REQUEST: small cards

### ISSUE THREAD

**Issue by bdillahu** [rmountjoy92/DashMachine#51]
Maybe an option for smaller cards? I love the card view, but they are pretty big.

Might fit well with Issue #46 (specify number of rows/columns)

Loving the product!

**Comment by auanasgheps** [comment]
I agree. The latest update (0.5) has taken away the ability to make cards smaller. 
Currently it is wasting a lot of space and having to scroll the screen even if you only have few apps!

**Comment by DaFlowah** [comment]
With smaller cards I believe it would be nice to be able to choose where to locate them (top, middle, right, left).
Hope you like the idea.

**Comment by rmountjoy92** [comment]
this has been address with addition of collections and the list view sidenav.
