### ISSUE TITLE
Add Tag Icon

### ISSUE THREAD

**Issue by SlowLogicBoy** [rmountjoy92/DashMachine#57]
Ability To Add Icon to a Tag

**Comment by whattheschnell** [comment]
I'm on 0.5-3, and I'm having issues with tag icons.  Is there a size limitation? 50x50 icon


tags = {"name": "House", "icon": "static/images/icons/icons8-home-50.png"}

**Comment by SlowLogicBoy** [comment]
#86

**Comment by rmountjoy92** [comment]
Actually current only supports material icon classes. You can find them here https://material.io/resources/icons/?icon=settings&style=outline

Note its just the class, eg 'info'.

**Comment by whattheschnell** [comment]
Do you have to download in /static/images/icons?  I don't get any in either case:

```
[Settings]
theme = dark
accent = blue
background = None
roles = admin,user,public_user
home_access_groups = admin_only
settings_access_groups = admin_only
custom_app_title = DashMachine
sidebar_default = open
tags_expanded = true
tags = 
{"name" = "House","icon": "import_export", "sort_pos" = 1}

[Home Assistant]
prefix = http://
url = 10.0.0.100:8123
icon = static/images/apps/home-assistant.png
sidebar_icon = static/images/apps/home-assistant.png
description = Open source home automation that puts local control and privacy first
open_in = new_tab
tags = House
```

**Comment by whattheschnell** [comment]
![image](https://user-images.githubusercontent.com/8886395/79228282-cf4cdf00-7e26-11ea-847d-882766b58200.png)

**Comment by rmountjoy92** [comment]
`{"name" = "House","icon": "import_export", "sort_pos" = 1}`

needs to be:

`{"name" : "House", "icon": "import_export", "sort_pos": 1}`
