### ISSUE TITLE
Will This run along side Apache2 on a raspberry pi

### ISSUE THREAD

**Issue by Mishka6783** [rmountjoy92/DashMachine#62]

**Comment by rmountjoy92** [comment]
This is very much dependent on your set up. For hosting alongside other web services, I suggest you look into Docker. If not you would just have to make sure Dashmachine and apache are running on different ports, using a proxy (eg. nginx) if needed. Please note that if you run DM without using the docker image, it will default to using the default flask development server, which is a security vulnerability, you would have to make sure to deploy it using a production server.
