### ISSUE TITLE
Cannot access login Screen

### ISSUE THREAD

**Issue by rxmii4269** [rmountjoy92/DashMachine#69]
I am trying to access the DashMachine web GUI and was greeted with an unauthorized page.
This is a newly created container.
![Screenshot from 2020-03-28 15-48-08](https://user-images.githubusercontent.com/49266906/77833478-9533cb80-710b-11ea-9803-14fe40891850.png)

**Comment by rxmii4269** [comment]
Found the issue. had to explicitly route to the login page using 

> "/login"
Since you're using flask I suggest you utilized a redirect to the login page each time with a flash message.

**Comment by rmountjoy92** [comment]
Thanks for the suggestion. There's not a redirect there for a reason. Also if you read the update notes before updating, you would have seen a warning about this.
