### ISSUE TITLE
Internal Server Error with Collection

### ISSUE THREAD

**Issue by bdillahu** [rmountjoy92/DashMachine#75]
Tried to create a collection - if it's in the config, I just get an "Internal Server Error" and have to clean out config.ini and restart the docker.

Tried with example code copy/paste from the docs... same issue.

Not sure where to find any more logs to see what's going wrong.

**Comment by bdillahu** [comment]
I don't think that fixed it... at least its still happening to me (if it doesn't have a tags= parameter).

**Comment by rmountjoy92** [comment]
confirmed, something else is messing up here.

**Comment by bdillahu** [comment]
Confirmed... that got it this time...

**Comment by molnarti** [comment]
this still does not seem to be fixed. adding this collection causes internal server error (using latest docker container)

```
[Network]
type = collection
icon = dns
urls = {"url": "http://192.168.50.1", "icon": "static/images/icons/mikrotik.png", "name": "Mikrotik router", "open_in": "new_tab"},{"url": "http://192.168.5.1", "icon": "static/images/icons/mikrotik.png", "name": "Telekom Huawei HG8245H Router", "open_in": "new_tab"},{"url" = "http://192.168.50.2", "icon": "static/images/icons/mikrotik.png", "name": "Cisco SG200-26P switch", "open_in": "new_tab"}
```

**Comment by rmountjoy92** [comment]
@molnarti There was one erroneous equal sign in you json, this should work:
`{"url": "http://192.168.50.1", "icon": "static/images/icons/mikrotik.png", "name": "Mikrotik router", "open_in": "new_tab"},{"url": "http://192.168.5.1", "icon": "static/images/icons/mikrotik.png", "name": "Telekom Huawei HG8245H Router", "open_in": "new_tab"},{"url" : "http://192.168.50.2", "icon": "static/images/icons/mikrotik.png", "name": "Cisco SG200-26P switch", "open_in": "new_tab"} `

**Comment by molnarti** [comment]
@rmountjoy92 thank you, i haven't noticed that. still such user mistakes should be handled more gracefully than throwing an internal server error and requiring complete container cleanup.

**Comment by rmountjoy92** [comment]
How it is currently being done makes it very difficult to expect every type of error a user can  make while adding stuff to the config. This is addressed in the next release.
