### ISSUE TITLE
adding a folder inside the static/images/apps/ causes faults

### ISSUE THREAD

**Issue by brianhenson** [rmountjoy92/DashMachine#83]
Operating System:  Ubuntu 18.04 (Bionic) 
Steps to reproduce: 
1. virtualenv --python=python3 DashMachineEnv
2. cd DashMachineEnv && source bin/activate
3. git clone https://github.com/rmountjoy92/DashMachine.git
4. cd DashMachine && pip install -r requirements.txt
5. python3 run.py
6. mkdir dashmachine/static/images/apps/custom
7. add images to directory
8. Add config referencing folder/images
9. end run.py
10. restart run.py and it will faill with this error

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    dashmachine_init()
  File "/root/dash/DashMachineEnv/DashMachine/dashmachine/main/utils.py", line 59, in dashmachine_init
    read_config()
  File "/root/dash/DashMachineEnv/DashMachine/dashmachine/main/read_config.py", line 231, in read_config
    tag_json = json.loads(tag_setting)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 46 (char 45)

**Comment by brianhenson** [comment]
config.ini


[Settings]
theme = dark
accent = orange
background = None
roles = admin,user,public_user
home_access_groups = public
settings_access_groups = admin_only
custom_app_title = Henson Home Page
sidebar_default = open
tags = {"name": "house", "icon":"home", "sort_pos":2},{"name": "Aden", "icon":"home", "sort_pos":1}, {"name": "Admin", "icon":"home", "sort_pos":3}
tags_expanded = True

[admin]
role = admin
password = 
confirm_password = 

[user2]
role = admin
password = 
confirm_password = 

[user1]
role = admin
password = 
confirm_password = 

[public]
roles = admin, user, public_user

[adm]
roles = admin, user

[Google Classroom]
prefix = https://
url = classroom.google.com/u/1/c/MzgwODMzMzkzNzBa
icon = static/images/apps/custom/gclass.png
description = Google Classroom
open_in = this_tab
groups = public
tags = Aden

[Blackboard]
prefix = https://
url = fcps.blackboard.com/
icon = static/images/apps/custom/bb.png
description = Blackboard
open_in = this_tab
groups = public
tags = House

[MyOn]
prefix = https://
url = www.myon.com/index.html
icon = static/images/apps/custom/myon.png
description = MyOn
open_in = this_tab
groups = public
tags = House

[ABCya]
prefix = http://
url = www.abcya.com/
icon = static/images/apps/custom/abcya.png
description = ABCya
open_in = this_tab
groups = public
tags = House

[Lunch Doodles]
prefix = https://
url = www.kennedy-center.org/mowillems
icon = static/images/apps/custom/lunch-doodles.png
description = Lunch Doodles
open_in = this_tab
groups = public
tags = House

[Minecraft Challenges]
prefix = https://
url = code.org/minecraft
icon = static/images/apps/custom/minecraft.png
description = Minecraft Challenge
open_in = this_tab
groups = public
tags = House

[PBS Kids]
prefix = https://
url = pbskids.org/
icon = static/images/apps/custom/pbs-kids.png
description = PBS Kids
open_in = this_tab
groups = public
tags = House

[BBC History]
prefix = https://
url = www.bbc.co.uk/history/forkids/
icon = static/images/apps/custom/bbchistory.jpg
description = BBC History
open_in = this_tab
groups = public
tags = House

[Highlights Kids]
prefix = https://
url = www.highlightskids.com/
icon = static/images/apps/custom/hkids.png
description = Highlights Kids
open_in = this_tab
groups = public
tags = House

[National Geographic Kids]
prefix = https://
url = kids.nationalgeographic.com/
icon = static/images/apps/custom/ngok.png
description = National Geographic Kids
open_in = this_tab
groups = public
tags = House

[The Kidz Page]
prefix = http://
url = www.thekidzpage.com/
icon = static/images/apps/custom/kidspage.png
description = The Kidz Page
open_in = this_tab
groups = public
tags = House

[Starfall]
prefix = https://
url = www.starfall.com/h/
icon = static/images/apps/custom/starfall.png
description = starfall
open_in = this_tab
groups = public
tags = House

[Smithsonian Learning]
prefix = https://
url = learninglab.si.edu/
icon = static/images/apps/custom/sll.png
description = Smithsonian Learning
open_in = this_tab
groups = public
tags = House

[National Art Gallery]
prefix = https://
url = www.nga.gov/education/kids.html
icon = static/images/apps/custom/nag.png
description = National Art Gallery
open_in = this_tab
groups = public
tags = House

[Funbrain]
prefix = https://
url = www.funbrain.com/
icon = static/images/apps/custom/funbrain.png
description = Funbrain
open_in = this_tab
groups = public
tags = House

[The Magic School Bus]
prefix = https://
url = kids.scholastic.com/kids/books/the-magic-school-bus/
icon = static/images/apps/custom/msb.png
description = The Magic School Bus
open_in = this_tab
groups = public
tags = House

[Make Me Genius]
prefix = https://
url = www.makemegenius.com/
icon = static/images/apps/custom/mmg.png
description = Make Me Genius
open_in = this_tab
groups = public
tags = House

[Animal Cameras]
prefix = https://
url = explore.org/livecams
icon = static/images/apps/custom/explore.png
description = Animal Cameras
open_in = this_tab
groups = public
tags = House

[Art for Kids Hub]
prefix = https://
url = www.youtube.com/user/ArtforKidsHub/videos
icon = static/images/apps/custom/artforkids.jpg
description = Art for Kids Hub
open_in = this_tab
groups = public
tags = House

[The Best of Sesame Street]
prefix = https://
url = https://www.commonsensemedia.org/lists/the-best-of-sesame-street
icon = static/images/apps/custom/sesame-street.jpg
description = Art for Kids Hub
open_in = this_tab
groups = public
tags = House

[Unifi]
prefix = https://
url = loki:8443/manage/manage
icon = static/images/apps/unifi.png
description = The UniFiÂ® Controller is a wireless network management software solution from Ubiquiti Networksâ„¢. It allows you to manage multiple wireless networks using a web browser.
open_in = this_tab
groups = adm
tags = admin

[Budget]
prefix = https://
url = docs.google.com/spreadsheets/d/1m6fS-K5HwcER-DI4FAjoWLTxFv0_L5VrtHFDD0hNdG8/edit
icon = static/images/apps/krusader.png
description = budget hosted on google docs
open_in = this_tab
groups = adm
tags = admin

[Watch Movies]
prefix = http://
url = loki:32400/web
icon = static/images/apps/plex.png
description = Plex is a clientâ€“server media player system and software suite.
open_in = this_tab
groups = public
tags = House

[Transmission]
prefix = http://
url = loki:9091/transmission/web/
icon = static/images/apps/transmission.png
description = A Fast, Easy, and Free BitTorrent Client
open_in = this_tab
groups = adm
tags = admin

**Comment by rmountjoy92** [comment]
You don't need to make a custom folder in the `static/images/apps` folder. In `static/images` there is a folder called `icons` which is symlinked to the `icons` folder in `user_data` which will persist updates. When you upload icons through the UI, they go into `static/images/icons`. `static/images/apps` is for template apps that are included with DashMachine.
