### ISSUE TITLE
Misleading Transmission datasource documentation

### ISSUE THREAD

**Issue by Berjou** [rmountjoy92/DashMachine#88]
The documentation of the the `Transmission` datasource says that the `user` and `password` fields are not required. However, if I omit one of this field, I got the following error: 

`AttributeError: 'Platform' object has no attribute 'user'`

I got the same error for the `password` field if I fill the `user` field but not the `password` field.

I was able to fix this problem just by declaring the user and password without associated value.

Thank you for this great tool!

**Comment by rmountjoy92** [comment]
Sounds good I'll update the documentation. Thanks!
