### ISSUE TITLE
Certain special characters are not allowed in passwords

### ISSUE THREAD

**Issue by Steven-Tuccio-wwt** [rmountjoy92/DashMachine#89]
Currently, it appears that some special characters are not allowed in passwords without crashing DashMachine

Identified Problem Characters:    %   
Characters that are not problematic:      *  &   !  ^   $   @    #

* To Test * 

Change admin user password to: aaaaaaaaaaaa
- Works successfully

Change admin password to: aaaaaa%aaaaa
 - Crashes DashMachine

**Comment by rmountjoy92** [comment]
I have noticed this too. There are situations where % throws off configparser, I will look into this.
