### ISSUE TITLE
Add readme for Pihole platform

### ISSUE THREAD

**Issue by rmountjoy92** [rmountjoy92/DashMachine#9]
I'm trying to use the pihole data source platform script. There is no help or read me that I can find for it and i'm unable to get data back.

My config going off errors and what I can understand of the code (sorry, not a dev) is below. Using this doesn't give me errors but all it outpus is the value of “value_template”

[pl_pihole]
platform = pihole
host = 192.168.1.101
password = [redacted]  <-- tried with plain text password and API token
value_template = topClients
UPDATE: I snooped the traffic it it is working with the password. I'm just unable to get it to display anything.

**Comment by rmountjoy92** [comment]
Never mind. I finally got it working. I should just read more and better.

[pl_pihole]
platform = pihole
host = 192.168.1.101
password = [redacted]
value_template = Ads Blocked Today: {{ blocked }} Status: {{ status }} Queries today: {{ queries }}
Any way I can insert a line break between varibles?

This is not an open issue.

**Comment by odinsride** [comment]
@rmountjoy92 Not sure if your question is still unanswered, but I got line breaks in the value_template for the transmission platform like this:

`value_template = 🔽 {{(downloadSpeed/1024/1024)|round(2)}} MB/s<br>🔼 {{(uploadSpeed/1024/1024)|round(2)}} MB/s<br><strong>Active:</strong> {{activeTorrentCount}}`
