### ISSUE TITLE
Feature Request: Add ability to toggle light/dark theme (siwtch on sidebar)

### ISSUE THREAD

**Issue by Thlb** [rmountjoy92/DashMachine#97]
Hi,

How about a button on the sidebar in order to switch light/dark theme ?

Thanks for your awesome dashboard. 💯

**Comment by rmountjoy92** [comment]
Should be pretty easy :)

**Comment by Thlb** [comment]
In addition, maybe change some settings : 
- background_light : background used for light theme
- background_dark : background used for dark theme
- accent_light : accent used for dark theme
- accent_dark : accent used for dark theme

**Comment by marcjmiller** [comment]
> In addition, maybe change some settings :
> 
> * background_light : background used for light theme
> * background_dark : background used for dark theme
> * accent_light : accent used for dark theme
> * accent_dark : accent used for dark theme

At least in React's material-ui, the accent/background colors are generated based off of given primary (and secondary) colors and theme type (dark/light).  So that should mostly be unneeded unless you mean different images based on theme type.

**Comment by rmountjoy92** [comment]
added in 6b362950f7a7e9a66ea36be7921ba1bc36a61b3e
I will look into adding the material dark/light variants for the accent colors. (pretty sure they're all just the light variants)
